server.port: 8080
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      show_sql: true
      format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secretKey: llshlllshlllshlllshlacdekcekwqnxxdeedcds

endpoint:
  key: G9fSpitmtAeKzYJC7X0SwA==

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /3o3/swagger.html
    disable-swagger-default-url: false
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - "/**"
